### ISSUE TITLE
Show toolbar at the bottom of the editor

### ISSUE THREAD

**Issue by ravipatel2293** [surmon-china/vue-quill-editor#409]
Hi,
First of all thank you so much for this library.

I have integrated this library in my one of the Vue project but I'm wondering how can I show toolbar at the bottom of the editor?

Is there any option available to achieve this? i was not able to find such a position option for toolbar. 

Greatly appreciate your help in this.

**Comment by jezsung** [comment]
``` css
.quill-editor {
  display: flex;
  flex-direction: column-reverse;
}
```
try this
