### ISSUE TITLE
About use inline style!

### ISSUE THREAD

**Issue by hezhongfeng** [surmon-china/vue-quill-editor#64]
This is a demo to use inline style.[demo](http://quilljs.com/playground/#class-vs-inline-style) 
I also check your 04-example.vue,but my code doesn't work.
It's my code.
```
<template>
  <div class="new-enter">
    <el-input v-model="title" placeholder="请输入标题"></el-input>
    <el-input v-model="author" placeholder="请输入作者"></el-input>
    <quill-editor class="editor" v-model="content" ref="myQuillEditor" :options="editorOption">
    </quill-editor>
    <div class="button-group">
      <el-button type="primary" icon="delete">清空</el-button>
      <el-button type="primary" icon="check">保存</el-button>
      <el-button type="primary" icon="share" @click="publish">发布审批</el-button>
    </div>
  </div>
</template>

<script>
const axios = require('axios');
import Quill from 'quill';
let SizeStyle = Quill.import('attributors/style/size');
Quill.register(SizeStyle, true);
export default {
  name: 'new-enter',
  data() {
    return {
      title: '',
      author: '',
      content: '',
      editorOption: {
        modules: {
          toolbar: [
            ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
            ['blockquote'],
            // ['blockquote', 'code-block'],
            // [{ 'header': 1 }, { 'header': 2 }, { 'header': 3 }],               // custom button values
            ['image'],
            [{ 'list': 'ordered' }, { 'list': 'bullet' }],
            // [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
            // [{ 'indent': '-1' }, { 'indent': '+1' }],          // outdent/indent
            // [{ 'direction': 'rtl' }],                         // text direction
            [{ 'size': ['small', false, 'large'] }],  // custom dropdown
            // [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
            [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
            // [{ 'font': [] }],
            [{ 'align': [] }]
            // ['clean']                                         // remove formatting button
          ]
        },
        placeholder: '从这里开始写正文'
      }
    };
  },
  methods: {
  },
  mounted() {

  }
};

</script>

</style>


```

**Comment by surmon-china** [comment]
Show the `'attributors/style/size'` code please.

**Comment by hezhongfeng** [comment]
[this is the code](https://github.com/quilljs/quill/blob/v1.2.6/formats/size.js)
[this is a assues](https://github.com/quilljs/quill/issues/1093)

**Comment by hezhongfeng** [comment]
@surmon-china 
Do you get my msg?

**Comment by surmon-china** [comment]
@hezhongfeng 
After my test, it can work properly.

Inline style(default):

![image](https://user-images.githubusercontent.com/14019524/28427628-67e38a84-6da9-11e7-89a7-6fa79b5d85fe.png)

Class style:

![image](https://user-images.githubusercontent.com/14019524/28427643-72a6a834-6da9-11e7-8ce4-46f1748692cc.png)

![image](https://user-images.githubusercontent.com/14019524/28427685-984c07a0-6da9-11e7-8601-5d498ac79f69.png)



But the class name is parsed to `ql-color-<#e60000>` and `ql-bg-#ff9900` this hexadecimal color value, so there is no css color application, the specific may be different from the `attribution` class, which can help you?

**Comment by hezhongfeng** [comment]
Thank you for your answer.
Can u test the 'font-size'? use inline style

**Comment by surmon-china** [comment]
@hezhongfeng 

![image](https://user-images.githubusercontent.com/14019524/28447396-11c72bba-6e03-11e7-8329-50bc8d200fde.png)

This problem is solved, the biggest problem is that you need to manually configure the `toolbar` option, he corresponding to each option` value` value will be inserted as inline data, good luck!

like this:

![image](https://user-images.githubusercontent.com/14019524/28447441-546eafba-6e03-11e7-9f89-7779891277f2.png)

In vue:

```html
<quill-editor ref="myTextEditor"
              v-model="content"
              :options="editorOption"
              @blur="onEditorBlur($event)"
              @focus="onEditorFocus($event)"
              @ready="onEditorReady($event)">
  <div id="toolbar" slot="toolbar">
    <span class="ql-formats">
      <select class="ql-size">
        <option value="10px">Small</option>
        <option selected>Normal</option>
        <option value="18px">Large</option>
        <option value="32px">Huge</option>
      </select>
    </span>
    <span class="ql-formats">
      <select class="ql-color">
        <option selected></option>
        <option value="red"></option>
        <option value="orange"></option>
        <option value="yellow"></option>
        <option value="green"></option>
        <option value="blue"></option>
        <option value="purple"></option>
      </select>
      <select class="ql-background">
        <option selected></option>
        <option value="red"></option>
        <option value="orange"></option>
        <option value="yellow"></option>
        <option value="green"></option>
        <option value="blue"></option>
        <option value="purple"></option>
      </select>
    </span>
  </div>
</quill-editor>
```

```javascript
editorOption: {
  modules: {
    toolbar: '#toolbar'
  },
  placeholder: 'Compose an epic...'
}
```

**Comment by SmileYuhao** [comment]
I met the same problem.
 It works with 
```js
let AlignStyle = Quill.import('attributors/style/align');
Quill.register(AlignStyle, true);
```

But if I add
```js
let SizeStyle = Quill.import('attributors/style/size');
Quill.register(SizeStyle, true);
```

The part of code is:
```js
container: [
    [{'size': []}],
],
```
The _font size_ no longer works. Maybe I miss something?

**Comment by usolved** [comment]
I could reproduce the same issue like @SmileYuhao.
As soon as I register the SizeStyle [{ 'size': ['small', false, 'large'] }] is no longer working.

Other "attributors/style/..." plugins are working fine. When I adapt the inline html method it is also working but also don't want to write the whole toolbar as html ;).

**Comment by hezhongfeng** [comment]
@SmileYuhao @usolved 
You can use quill directly
For other reasons，eventually I used [tinymce](https://www.tinymce.com/)

**Comment by usolved** [comment]
I have a reason why I like to use the Vue.js version of Quill ;)

Maybe I'll create a new issue since it's not really fixed and closed with a workaround.

**Comment by loveshinee** [comment]
Here is my solution to set inline styles for the font-size in quill :
1.
![image](https://user-images.githubusercontent.com/9989837/35859269-65890f2e-0b7a-11e8-8306-49492f915cc6.png)
2. 
![image](https://user-images.githubusercontent.com/9989837/35859310-7d3883de-0b7a-11e8-8245-c5755e0139f3.png)
3. 
css also need to be modified to control the toolbar's size options
![image](https://user-images.githubusercontent.com/9989837/35859353-ab0ba69c-0b7a-11e8-9094-bc673be2d8bb.png)




￼

**Comment by wakaryry** [comment]
@loveshinee But the size can only be set to 10 18 32. 
Any way for other size?
We need 10, 12,14...32.

**Comment by wakaryry** [comment]
I added the `whitelist` based on the solution @loveshinee .
### 1. register
``` js
import { Quill } from 'vue-quill-editor'
const sizeStyle = Quill.import('attributors/style/size')
sizeStyle.whitelist = ['10px', '12px', '14px', '16px', '18px', '20px', '24px', '30px', '32px', '36px']
Quill.register(sizeStyle, true)
```

### 2. change size options
```js
[{ 'size': [false, '10px', '12px', '14px', '16px', '18px', '20px', '24px', '30px', '32px', '36px'] }]
```

### 3. add some css in `quill/dist/quill.core.css`
```css
.ql-picker-item[data-value='10px']::before, .ql-picker-label[data-value='10px']::before {
  content: '10px' !important;
}

.ql-picker-item[data-value='12px']::before, .ql-picker-label[data-value='12px']::before {
  content: '12px' !important;
}

.ql-picker-item[data-value='14px']::before, .ql-picker-label[data-value='14px']::before {
  content: '14px' !important;
}

.ql-picker-item[data-value='16px']::before, .ql-picker-label[data-value='16px']::before {
  content: '16px' !important;
}

.ql-picker-item[data-value='18px']::before, .ql-picker-label[data-value='18px']::before {
  content: '18px' !important;
}

.ql-picker-item[data-value='20px']::before, .ql-picker-label[data-value='20px']::before {
  content: '20px' !important;
}

.ql-picker-item[data-value='24px']::before, .ql-picker-label[data-value='24px']::before {
  content: '24px' !important;
}

.ql-picker-item[data-value='30px']::before, .ql-picker-label[data-value='30px']::before {
  content: '30px' !important;
}

.ql-picker-item[data-value='32px']::before, .ql-picker-label[data-value='32px']::before {
  content: '32px' !important;
}

.ql-picker-item[data-value='36px']::before, .ql-picker-label[data-value='36px']::before {
  content: '36px' !important;
}
```

It seems worked.
